[main] ERROR com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl  - Unknown database 'ormdb'
java.sql.SQLSyntaxErrorException: Unknown database 'ormdb'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:28)
	at com.saraya.AnotherJdbcProject.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:11)
	at com.saraya.AnotherJdbcProject.ClientApplication.main(ClientApplication.java:14)
[main] ERROR com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:47)
	at com.saraya.AnotherJdbcProject.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:11)
	at com.saraya.AnotherJdbcProject.ClientApplication.main(ClientApplication.java:14)
[main] INFO  com.saraya.AnotherJdbcProject.ClientApplication  - Records are successfully added..
[main] ERROR com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl  - The server time zone value 'Est (heure d��t�)' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
java.sql.SQLException: The server time zone value 'Est (heure d��t�)' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:28)
	at com.saraya.AnotherJdbcProject.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:11)
	at com.saraya.AnotherJdbcProject.ClientApplication.main(ClientApplication.java:14)
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'Est (heure d��t�)' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2118)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2142)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 8 more
[main] ERROR com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.AnotherJdbcProject.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:47)
	at com.saraya.AnotherJdbcProject.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:11)
	at com.saraya.AnotherJdbcProject.ClientApplication.main(ClientApplication.java:14)
[main] INFO  com.saraya.AnotherJdbcProject.ClientApplication  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - resources\application.properties (The system cannot find the path specified)
java.io.FileNotFoundException: resources\application.properties (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:21)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:49)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - resources\application.properties (The system cannot find the path specified)
java.io.FileNotFoundException: resources\application.properties (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:21)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:49)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - resources\application.properties (The system cannot find the path specified)
java.io.FileNotFoundException: resources\application.properties (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:21)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:49)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - resources\application.properties (The system cannot find the path specified)
java.io.FileNotFoundException: resources\application.properties (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:21)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:49)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - resources\application.properties (The system cannot find the path specified)
java.io.FileNotFoundException: resources\application.properties (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:21)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.close()" because "this.stmt" is null
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:49)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Data truncation: Out of range value for column 'phoneNumber' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'phoneNumber' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:42)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Data truncation: Out of range value for column 'phoneNumber' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'phoneNumber' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:42)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Data truncation: Out of range value for column 'phoneNumber' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'phoneNumber' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:42)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Data truncation: Out of range value for column 'phoneNumber' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'phoneNumber' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:42)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Data truncation: Out of range value for column 'phoneNumber' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'phoneNumber' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.insert(CustomerDAOImpl.java:42)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.insert(CustomerServiceImpl.java:12)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:16)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phone_no' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phone_no' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phone_no' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phone_no' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phone_no' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phone_no' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phoneNo' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phoneNo' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phonNo' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phonNo' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phone_no' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phone_no' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
[main] INFO  com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Record inserted
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Records are successfully added..
[main] ERROR com.saraya.simple_project_jdbc.dao.CustomerDAOImpl  - Unknown column 'phone_no' in 'where clause'
java.sql.SQLSyntaxErrorException: Unknown column 'phone_no' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.saraya.simple_project_jdbc.dao.CustomerDAOImpl.remove(CustomerDAOImpl.java:75)
	at com.saraya.simple_project_jdbc.service.CustomerServiceImpl.remove(CustomerServiceImpl.java:16)
	at com.saraya.simple_project_jdbc.CustomerApp.main(CustomerApp.java:21)
[main] INFO  com.saraya.simple_project_jdbc.CustomerApp  - Success : Record deleted successfully 
